version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - chat-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: chat-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - chat-network
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  chat-network:
    driver: bridge